In [1]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\carlos\anaconda3\lib\site-packages (4.0.0-unsupported)

In [34]:
import requests
import pandas as pd
import pyodbc as pyo
from datetime import date

In [35]:
# creating a df
df = pd.DataFrame(columns=["id",
                           "created_at",
                           "reference",
                           "pac_values_1",
                           "pac_values_2",
                           "pac_values_3",
                           "pac_values_4",
                           "total_energy_values_1",
                           "total_energy_values_2",
                           "total_energy_values_3",
                           "total_energy_values_4",
                           "year_energy_values_1",
                           "year_energy_values_2",
                           "year_energy_values_3",
                           "year_energy_values_4",
                           "year_energy_unit",
                           ])

In [36]:
date = "20220515"
url = 'https://data.exia.com.co/demo/inverter/fronius?date=' + date
response = requests.get(url).json()

while(date)

for count in response:
    id = count['id']
    created_at = count['created_at']
    #date = str(count['created_at']).split(' ')
    #energyreal_wac_sum_consumed = count['energyreal_wac_sum_consumed']
    #energyreal_wac_sum_produced = count['energyreal_wac_sum_produced']
    #current_ac_sum = count['current_ac_sum']
    #powerreal_p_sum = count['powerreal_p_sum']
    reference = count['reference']
    #voltage_ac_phase_average = count['voltage_ac_phase_average']
    pac_values_1 = count['pac_values_1']
    pac_values_2 = count['pac_values_2']
    pac_values_3 = count['pac_values_3']
    pac_values_4 = count['pac_values_4']
    total_energy_values_1 = count['total_energy_values_1']
    total_energy_values_2 = count['total_energy_values_2']
    total_energy_values_3 = count['total_energy_values_3']
    total_energy_values_4 = count['total_energy_values_4']
    year_energy_values_1 = count['year_energy_values_1']
    year_energy_values_2 = count['year_energy_values_2']
    year_energy_values_3 = count['year_energy_values_3']
    year_energy_values_4 = count['year_energy_values_4']
    year_energy_unit = count['year_energy_unit']
    
    

    #save data into df
    df = df.append({"id": id,
              "created_at": created_at,
              "reference": reference,
              "pac_values_1":pac_values_1,
              "pac_values_2": pac_values_2,
              "pac_values_3": pac_values_3,
              "pac_values_4": pac_values_4,
              "total_energy_values_1":total_energy_values_1,
              "total_energy_values_2": total_energy_values_2,
              "total_energy_values_3": total_energy_values_3,
              "total_energy_values_4": total_energy_values_4,
              "year_energy_values_1": year_energy_values_1,
              "year_energy_values_2": year_energy_values_2,
              "year_energy_values_3": year_energy_values_3,
              "year_energy_values_4": year_energy_values_4,
              "year_energy_unit": year_energy_unit,
                    
              }, ignore_index=True)

In [37]:
response

[{'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 31184.0,
  'day_energy_values_2': 37770.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902952,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 7741370.0,
  'total_energy_values_2': 9470760.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'May 15 2022 05:00:03',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 5072560.0,
  'year_energy_values_2': 6278260.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 23933.0,
  'day_energy_values_2': 23874.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 15895.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902953,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 12149700.0,
  'total_energy_values_2': 12001400.0,
  'total_energy_values_3': 7372590.0,
  'total_energy_values_4': 7259250.0,
  'update_at': 'May 15 2022 05:00:04',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 6928910.0,
  'year_energy_values_2': 6869620.0,
  'year_energy_values_3': 4230260.0,
  'year_energy_values_4': 4082370.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 31184.0,
  'day_energy_values_2': 37770.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902954,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 7741370.0,
  'total_energy_values_2': 9470760.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'May 15 2022 05:00:12',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 5072560.0,
  'year_energy_values_2': 6278260.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 23933.0,
  'day_energy_values_2': 23874.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 15895.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902955,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 12149700.0,
  'total_energy_values_2': 12001400.0,
  'total_energy_values_3': 7372590.0,
  'total_energy_values_4': 7259250.0,
  'update_at': 'May 15 2022 05:00:13',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 6928910.0,
  'year_energy_values_2': 6869620.0,
  'year_energy_values_3': 4230260.0,
  'year_energy_values_4': 4082370.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 31184.0,
  'day_energy_values_2': 37770.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902956,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 7741370.0,
  'total_energy_values_2': 9470760.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'May 15 2022 05:00:22',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 5072560.0,
  'year_energy_values_2': 6278260.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 0.0,
  'day_energy_values_2': 23874.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 15895.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902957,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 12149700.0,
  'total_energy_values_2': 12001400.0,
  'total_energy_values_3': 7372590.0,
  'total_energy_values_4': 7259250.0,
  'update_at': 'May 15 2022 05:00:23',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 6928910.0,
  'year_energy_values_2': 6869620.0,
  'year_energy_values_3': 4230260.0,
  'year_energy_values_4': 4082370.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 31184.0,
  'day_energy_values_2': 37770.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902958,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 7741370.0,
  'total_energy_values_2': 9470760.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'May 15 2022 05:00:32',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 5072560.0,
  'year_energy_values_2': 6278260.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 0.0,
  'day_energy_values_2': 23874.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 15895.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902959,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 12149700.0,
  'total_energy_values_2': 12001400.0,
  'total_energy_values_3': 7372590.0,
  'total_energy_values_4': 7259250.0,
  'update_at': 'May 15 2022 05:00:33',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 6928910.0,
  'year_energy_values_2': 6869620.0,
  'year_energy_values_3': 4230260.0,
  'year_energy_values_4': 4082370.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 31184.0,
  'day_energy_values_2': 37770.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902960,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 7741370.0,
  'total_energy_values_2': 9470760.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'May 15 2022 05:00:42',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 5072560.0,
  'year_energy_values_2': 6278260.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': None,
  'created_at': 'May 15 2022 00:00:00',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 0.0,
  'day_energy_values_2': 23874.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 15895.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 2902961,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 12149700.0,
  'total_energy_values_2': 12001400.0,
  'total_energy_values_3': 7372590.0,
  'total_energy_values_4': 7259250.0,
  'update_at': 'May 15 2022 05:00:43',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 6928910.0,
  'year_energy_values_2': 6869620.0,
  'year_energy_values_3': 4230260.0,
  'year_energy_values_4': 4082370.0}]

In [38]:
df.head(2000)

,id,created_at,reference,pac_values_1,pac_values_2,pac_values_3,pac_values_4,total_energy_values_1,total_energy_values_2,total_energy_values_3,total_energy_values_4,year_energy_values_1,year_energy_values_2,year_energy_values_3,year_energy_values_4,year_energy_unit
0,2902952,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
1,2902953,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
2,2902954,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
3,2902955,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
4,2902956,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
5,2902957,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
6,2902958,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
7,2902959,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
8,2902960,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
9,2902961,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh

In [39]:
df.sort_values(by=['id'], ascending=False)
df.head(2000)

,id,created_at,reference,pac_values_1,pac_values_2,pac_values_3,pac_values_4,total_energy_values_1,total_energy_values_2,total_energy_values_3,total_energy_values_4,year_energy_values_1,year_energy_values_2,year_energy_values_3,year_energy_values_4,year_energy_unit
0,2902952,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
1,2902953,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
2,2902954,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
3,2902955,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
4,2902956,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
5,2902957,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
6,2902958,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
7,2902959,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh
8,2902960,May 15 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7741370.0,9470760.0,0.0,0.0,5072560.0,6278260.0,0.0,0.0,Wh
9,2902961,May 15 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12149700.0,12001400.0,7372590.0,7259250.0,6928910.0,6869620.0,4230260.0,4082370.0,Wh

In [40]:
df.to_csv('dataInverter3.csv',index=False)