In [41]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\carlos\anaconda3\lib\site-packages (4.0.0-unsupported)

In [49]:
import requests
import pandas as pd
import pyodbc as pyo
from datetime import date

In [50]:
# creating a df
df = pd.DataFrame(columns=["id",
                           "created_at",
                           "reference",
                           "pac_values_1",
                           "pac_values_2",
                           "pac_values_3",
                           "pac_values_4",
                           "total_energy_values_1",
                           "total_energy_values_2",
                           "total_energy_values_3",
                           "total_energy_values_4",
                           "year_energy_values_1",
                           "year_energy_values_2",
                           "year_energy_values_3",
                           "year_energy_values_4",
                           "year_energy_unit",
                           ])

In [611]:
date = "2022011"
url = 'https://data.exia.com.co/demo/inverter/fronius?date=' + date
response = requests.get(url).json()

for count in response:
    id = count['id']
    created_at = count['created_at']
    #date = str(count['created_at']).split(' ')
    #energyreal_wac_sum_consumed = count['energyreal_wac_sum_consumed']
    #energyreal_wac_sum_produced = count['energyreal_wac_sum_produced']
    #current_ac_sum = count['current_ac_sum']
    #powerreal_p_sum = count['powerreal_p_sum']
    reference = count['reference']
    #voltage_ac_phase_average = count['voltage_ac_phase_average']
    pac_values_1 = count['pac_values_1']
    pac_values_2 = count['pac_values_2']
    pac_values_3 = count['pac_values_3']
    pac_values_4 = count['pac_values_4']
    total_energy_values_1 = count['total_energy_values_1']
    total_energy_values_2 = count['total_energy_values_2']
    total_energy_values_3 = count['total_energy_values_3']
    total_energy_values_4 = count['total_energy_values_4']
    year_energy_values_1 = count['year_energy_values_1']
    year_energy_values_2 = count['year_energy_values_2']
    year_energy_values_3 = count['year_energy_values_3']
    year_energy_values_4 = count['year_energy_values_4']
    year_energy_unit = count['year_energy_unit']
    
    

    #save data into df
    df = df.append({"id": id,
              "created_at": created_at,
              "reference": reference,
              "pac_values_1":pac_values_1,
              "pac_values_2": pac_values_2,
              "pac_values_3": pac_values_3,
              "pac_values_4": pac_values_4,
              "total_energy_values_1":total_energy_values_1,
              "total_energy_values_2": total_energy_values_2,
              "total_energy_values_3": total_energy_values_3,
              "total_energy_values_4": total_energy_values_4,
              "year_energy_values_1": year_energy_values_1,
              "year_energy_values_2": year_energy_values_2,
              "year_energy_values_3": year_energy_values_3,
              "year_energy_values_4": year_energy_values_4,
              "year_energy_unit": year_energy_unit,
                    
              }, ignore_index=True)

In [612]:
response

[{'counter': 0,
  'created_at': 'Feb 01 2022 00:00:02',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 73870.0,
  'day_energy_values_2': 71450.0,
  'day_energy_values_3': 47660.0,
  'day_energy_values_4': 46820.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276551,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 6510050.0,
  'total_energy_values_2': 6388470.0,
  'total_energy_values_3': 3949730.0,
  'total_energy_values_4': 3975110.0,
  'update_at': 'Feb 01 2022 00:00:02',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 1289270.0,
  'year_energy_values_2': 1256650.0,
  'year_energy_values_3': 807403.0,
  'year_energy_values_4': 798237.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:04',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 35420.0,
  'day_energy_values_2': 46740.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276552,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 3619270.0,
  'total_energy_values_2': 4544620.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'Feb 01 2022 00:00:04',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 950462.0,
  'year_energy_values_2': 1352120.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:12',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 73870.0,
  'day_energy_values_2': 71450.0,
  'day_energy_values_3': 47660.0,
  'day_energy_values_4': 46820.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276553,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 6510050.0,
  'total_energy_values_2': 6388470.0,
  'total_energy_values_3': 3949730.0,
  'total_energy_values_4': 3975110.0,
  'update_at': 'Feb 01 2022 00:00:12',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 1289270.0,
  'year_energy_values_2': 1256650.0,
  'year_energy_values_3': 807403.0,
  'year_energy_values_4': 798237.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:13',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 35420.0,
  'day_energy_values_2': 46740.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276554,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 3619270.0,
  'total_energy_values_2': 4544620.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'Feb 01 2022 00:00:13',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 950462.0,
  'year_energy_values_2': 1352120.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:22',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 73870.0,
  'day_energy_values_2': 71450.0,
  'day_energy_values_3': 47660.0,
  'day_energy_values_4': 46820.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276555,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 6510050.0,
  'total_energy_values_2': 6388470.0,
  'total_energy_values_3': 3949730.0,
  'total_energy_values_4': 3975110.0,
  'update_at': 'Feb 01 2022 00:00:22',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 1289270.0,
  'year_energy_values_2': 1256650.0,
  'year_energy_values_3': 807403.0,
  'year_energy_values_4': 798237.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:24',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 35420.0,
  'day_energy_values_2': 46740.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276556,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 3619270.0,
  'total_energy_values_2': 4544620.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'Feb 01 2022 00:00:24',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 950462.0,
  'year_energy_values_2': 1352120.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:32',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 73870.0,
  'day_energy_values_2': 71450.0,
  'day_energy_values_3': 47660.0,
  'day_energy_values_4': 46820.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276557,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 6510050.0,
  'total_energy_values_2': 6388470.0,
  'total_energy_values_3': 3949730.0,
  'total_energy_values_4': 3975110.0,
  'update_at': 'Feb 01 2022 00:00:32',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 1289270.0,
  'year_energy_values_2': 1256650.0,
  'year_energy_values_3': 807403.0,
  'year_energy_values_4': 798237.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:34',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 35420.0,
  'day_energy_values_2': 46740.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276558,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 3619270.0,
  'total_energy_values_2': 4544620.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'Feb 01 2022 00:00:34',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 950462.0,
  'year_energy_values_2': 1352120.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:42',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 73870.0,
  'day_energy_values_2': 71450.0,
  'day_energy_values_3': 47660.0,
  'day_energy_values_4': 46820.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276559,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'comfenalco1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 6510050.0,
  'total_energy_values_2': 6388470.0,
  'total_energy_values_3': 3949730.0,
  'total_energy_values_4': 3975110.0,
  'update_at': 'Feb 01 2022 00:00:42',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 1289270.0,
  'year_energy_values_2': 1256650.0,
  'year_energy_values_3': 807403.0,
  'year_energy_values_4': 798237.0},
 {'counter': 0,
  'created_at': 'Feb 01 2022 00:00:44',
  'day_energy_unit': 'Wh',
  'day_energy_values_1': 35420.0,
  'day_energy_values_2': 46740.0,
  'day_energy_values_3': 0.0,
  'day_energy_values_4': 0.0,
  'head_requestarguments_query': 'Inverter',
  'head_requestarguments_scope': 'System',
  'head_status_code': '0',
  'head_status_reason': '',
  'head_status_usermessage': '',
  'id': 1276560,
  'pac_unit': 'W',
  'pac_values_1': 0.0,
  'pac_values_2': 0.0,
  'pac_values_3': 0.0,
  'pac_values_4': 0.0,
  'reference': 'takurika1-inverter',
  'total_energy_unit': 'Wh',
  'total_energy_values_1': 3619270.0,
  'total_energy_values_2': 4544620.0,
  'total_energy_values_3': 0.0,
  'total_energy_values_4': 0.0,
  'update_at': 'Feb 01 2022 00:00:44',
  'year_energy_unit': 'Wh',
  'year_energy_values_1': 950462.0,
  'year_energy_values_2': 1352120.0,
  'year_energy_values_3': 0.0,
  'year_energy_values_4': 0.0}]

In [613]:
df.head(2000)

,id,created_at,reference,pac_values_1,pac_values_2,pac_values_3,pac_values_4,total_energy_values_1,total_energy_values_2,total_energy_values_3,total_energy_values_4,year_energy_values_1,year_energy_values_2,year_energy_values_3,year_energy_values_4,year_energy_unit
0,2936519,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
1,2936520,May 17 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12247400.0,12098000.0,7433990.0,7323660.0,7026640.0,6966170.0,4291660.0,4146790.0,Wh
2,2936521,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
3,2936522,May 17 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12247400.0,12098000.0,7433990.0,7323660.0,7026640.0,6966170.0,4291660.0,4146790.0,Wh
4,2936523,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1276556,Feb 01 2022 00:00:24,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh
1116,1276557,Feb 01 2022 00:00:32,comfenalco1-inverter,0.0,0.0,0.0,0.0,6510050.0,6388470.0,3949730.0,3975110.0,1289270.0,1256650.0,807403.0,798237.0,Wh
1117,1276558,Feb 01 2022 00:00:34,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh
1118,1276559,Feb 01 2022 00:00:42,comfenalco1-inverter,0.0,0.0,0.0,0.0,6510050.0,6388470.0,3949730.0,3975110.0,1289270.0,1256650.0,807403.0,798237.0,Wh
1119,1276560,Feb 01 2022 00:00:44,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh

In [614]:
df.sort_values(by=['id'], ascending=False)
df.head(2000)

,id,created_at,reference,pac_values_1,pac_values_2,pac_values_3,pac_values_4,total_energy_values_1,total_energy_values_2,total_energy_values_3,total_energy_values_4,year_energy_values_1,year_energy_values_2,year_energy_values_3,year_energy_values_4,year_energy_unit
0,2936519,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
1,2936520,May 17 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12247400.0,12098000.0,7433990.0,7323660.0,7026640.0,6966170.0,4291660.0,4146790.0,Wh
2,2936521,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
3,2936522,May 17 2022 00:00:00,comfenalco1-inverter,0.0,0.0,0.0,0.0,12247400.0,12098000.0,7433990.0,7323660.0,7026640.0,6966170.0,4291660.0,4146790.0,Wh
4,2936523,May 17 2022 00:00:00,takurika1-inverter,0.0,0.0,0.0,0.0,7780600.0,9517900.0,0.0,0.0,5111800.0,6325400.0,0.0,0.0,Wh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1276556,Feb 01 2022 00:00:24,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh
1116,1276557,Feb 01 2022 00:00:32,comfenalco1-inverter,0.0,0.0,0.0,0.0,6510050.0,6388470.0,3949730.0,3975110.0,1289270.0,1256650.0,807403.0,798237.0,Wh
1117,1276558,Feb 01 2022 00:00:34,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh
1118,1276559,Feb 01 2022 00:00:42,comfenalco1-inverter,0.0,0.0,0.0,0.0,6510050.0,6388470.0,3949730.0,3975110.0,1289270.0,1256650.0,807403.0,798237.0,Wh
1119,1276560,Feb 01 2022 00:00:44,takurika1-inverter,0.0,0.0,0.0,0.0,3619270.0,4544620.0,0.0,0.0,950462.0,1352120.0,0.0,0.0,Wh

In [615]:
df.to_csv('dataInverter.csv',index=False)